name: xray-ag-ci
user: abhishek-goyal-tfs      # DKube login user name
parameters:
  class: training
  training:
    executor:
      choice: dkube
      buildfromproject: false
      dkube:
        framework:
          choice: tensorflow
          details:
            version: 2.0.0
            image: 'ocdr/dkube-datascience-tf-cpu:v2.0.0-17'
    datums:
      workspace:
        data:
          name: 'abhishek-goyal-tfs:xray-ag-v1'    # <Dkube login name>:<Code repo name>
          version: ''
        script: python chest-xray/training.py
      datasets:
        - name: 'abhishek-goyal-tfs:xray-ag-v1'    # <Dkube login name>:<Dataset repo name>
          mountpath: '/data'
      outputs:
        - name: 'abhishek-goyal-tfs:xray-ag-v1'    # <DKube login name>:<Model repo name>
          mountpath: '/model'
    featuresets: {}
    tags: []
    hyperparams:
      customkv:
        - key: EPOCHS
          value: '1'
      file:
        name: ''
        body: ''
    nworkers: 0
    ngpus: 0
    gpus_override: false
    rdma: false
    hptuning:
      name: ''
      body: ''
  run:
    template: ''
    group: default
